  version: "3.9"

  services:
    db:
      image: postgres:15
      restart: always
      environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
        POSTGRES_DB: testovoe_db
      ports:
        - "5432:5432"
      volumes:
        - postgres_data:/var/lib/postgresql/data

    app:
      build: .
      depends_on:
        - db
      env_file:
        - .env
      environment:
        DB_URL: postgresql+asyncpg://postgres:postgres@db:5432/testovoe_db
      ports:
        - "8000:8000"
      volumes:
        - .:/app

  volumes:
    postgres_data:
