"""Add test user and admin

Revision ID: 5f6efea6ffae
Revises: 50df3c0b76bc
Create Date: 2025-08-07 13:22:05.782181

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.sql import table, column
from sqlalchemy import String, Integer, Text, Boolean
import hashlib
import uuid


# revision identifiers, used by Alembic.
revision: str = '5f6efea6ffae'
down_revision: Union[str, Sequence[str], None] = '50df3c0b76bc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


user_table = table(
    'user',
    column('id', Integer),
    column('email', String),
    column('full_name', String),
    column('hashed_password', String),
    column('role', String)
)

account_table = table(
    'account',
    column('id', Integer),
    column('user_id', Integer),
    column('balance', Integer),
    column('name', String),
)

def upgrade() -> None:
    """Upgrade schema."""
    op.bulk_insert(user_table, [
        {
            "id": 1,
            "email": "admin@example.com",
            "full_name": "test_admin",
            "hashed_password": hashlib.sha256("admin123".encode()).hexdigest(),
            "role": "admin"
        },
        {
            "id": 2,
            "email": "user@example.com",
            "full_name": "test_user",
            "hashed_password": hashlib.sha256("user123".encode()).hexdigest(),
            "role": "user"
        }
    ])

    
    op.bulk_insert(account_table, [
        {
            "id": 1,
            "user_id": 2,
            "balance": 1000,
            "name": "Основной счет"
        }
    ])


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
