"""Update Payment added transactionID

Revision ID: 7d35b1fb5bb1
Revises: a1a282802956
Create Date: 2025-08-06 00:13:37.162434

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7d35b1fb5bb1'
down_revision: Union[str, Sequence[str], None] = 'a1a282802956'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payment', sa.Column('transaction_id', sa.String(length=36), nullable=False))
    op.create_index(op.f('ix_payment_transaction_id'), 'payment', ['transaction_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_payment_transaction_id'), table_name='payment')
    op.drop_column('payment', 'transaction_id')
    # ### end Alembic commands ###
