"""Removed payment_id

Revision ID: 933e713af4e9
Revises: 7d35b1fb5bb1
Create Date: 2025-08-06 11:53:50.068865

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '933e713af4e9'
down_revision: Union[str, Sequence[str], None] = '7d35b1fb5bb1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('payment_payment_id_key'), 'payment', type_='unique')
    op.drop_column('payment', 'payment_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payment', sa.Column('payment_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False))
    op.create_unique_constraint(op.f('payment_payment_id_key'), 'payment', ['payment_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
